trigger:
- main

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Building the app..."
      displayName: 'Build'

- stage: DeployToStaging
  displayName: 'Deploy to Staging'
  dependsOn: Build
  jobs:
  - deployment: DeployJob
    displayName: 'Staging Deployment Job'
    environment: staging   # <-- This is key. You must create this in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploying to staging..."
            displayName: 'Run Deployment Script'
