trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Job1
  steps:
  - script: echo "Running Job 1"

- job: Job2
  steps:
  - script: echo "Running Job 2"

- job: Job3
  steps:
  - script: echo "Running Job 3"
