trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
    
    
  - stage: Deploy
    displayName: Deploy
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy
      - deployment: Manual_approval
        environment: staging
        pool: server
        strategy: 
         runOnce:
           deploy:
             steps:
               - task: ManualValidation@1
                 inputs:
                   notifyUsers: 'abc@gmail.com'
                   instructions: 'Please approve'
            

             




