# When manually running the pipeline, you can select whether it
# succeeds or fails.
trigger:
- error
  
pool:
    vmImage: ubuntu-latest
  
    jobs:
      - job: A
        steps:
        - bash: echo "A"
      
      - job: B
        steps:
        - bash: echo "B"