trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build

  - stage: Dev1
    displayName: Dev1
    dependsOn: Build
    jobs:
      - deployment: Manual
        environment: Dev1
        pool: Server
        strategy:
          runOnce:
            deploy:
              steps:
                - task: ManualValidation@1
                  inputs:
                    notifyUsers: 'abc@gmail.com'
                    approvers: 'abc@'
                    instructions: 'please approve'