# When manually running the pipeline, you can select whether it
# succeeds or fails.
parameters:
- name: succeed
  displayName: Succeed or fail
  type: boolean
  default: false

pr:
- qqererer

trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: 
  steps:
  - script: echo Hello, i am fine!
    displayName: 'Run a one-line script'



