# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'LocalAgentPrisco'

stages:
- stage: Greeting
  jobs: 
  - job: greetingjob
    steps:
    - task: job@1
      inputs:
        command: 'echo ciaooo'
