trigger: none

pr:
- main

pool:
  vmImage: windows-latest

jobs:
  - job: GetRequestID
    displayName: Get Pull Request ID
    steps:
      - task: PowerShell@2
        inputs:
          targetType: inline
          script: Write-Host "PR ID is:" $(System.PullRequest.PullRequestNumber)
