trigger: none

pr:
- main

pool:
  vmImage: windows-latest

jobs:
  - job: GetRequestID
    displayName: Get Pull Request ID
    steps:
      - task: PowerShell@2
        inputs:
          targetType: inline
          script: |
            $upload = curl https://api.github.com/repos/akshayaravindan/REPO/pulls/PULL_NUMBER/files
            echo ($upload | ConvertFrom-Json).filename

