trigger:
  - main

pool: 
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build Stage
    dependsOn: []
    jobs:
       - job:
         displayName: Job1

  - stage: Dev1_EUW
    displayName: Dev1
    dependsOn: 
    - Build
    jobs:
      - job:
        displayName: Job2

             