trigger:
  - main

pool: 
  vmImage: 'ubuntu-latest'

stages:
  - stage: 
    displayName: Stage1
    dependsOn: []
    jobs:
       - job:
         displayName: Job1

  - stage: 
    displayName: Stage2
    dependsOn: []
    jobs:
      - job:
        displayName: Job2

  - stage: 
    displayName: Stage3
    dependsOn: 
    - Stage1
    - Stage2
    jobs:
      - job:
        displayName: Job3
             